# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id = omnixerio_redstone
mod_version = 0.1.0
maven_group = dev.ultreon.mods
archives_name = omnixerio-redstone
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.0.1
fabric_loader_version = 0.19.3
fabric_api_version = 0.152.0
neoforge_version = 26.2.0.1-beta